input:
  classifier_data_path: 'data/classifier_data.pkl'
  
output:
  model_path: 'models/classifier.pkl'
control:
  cv_folds: 5
  cv_repeats: 1
  random_state: 42
  regularization_penalties: [1, 1.e-1, 1.e-2, 1.e-3, 1.e-4, 1.e-5]
